b''
b''
b''
Dataset generated
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    run_data, training_name = run_training(alpha)
  File "main.py", line 90, in run_training
    tr_nam
NameError: name 'tr_nam' is not defined